from datetime import datetime
from typing import Optional
from pydantic import BaseModel, field_validator
from utilities.date_converter import to_gmt8


class IbankFtTransaction(BaseModel):
    msg_id: Optional[str] = ""
    aux_no: Optional[str] = ""
    sndr: Optional[str] = ""
    chal_valdt: Optional[str] = ""
    msg_grp_id: Optional[str] = ""
    card_no: Optional[str] = ""
    fr_acc_id: Optional[str] = ""
    fr_acc_lbl: Optional[str] = ""
    to_acc_id: Optional[str] = ""
    to_acc_lbl: Optional[str] = ""
    org_bnk_cod: Optional[str] = ""
    dest_bnk_cod: Optional[str] = ""
    dell: Optional[str] = ""
    org_brch_cod: Optional[str] = ""
    dest_brch_cod: Optional[str] = ""
    trx_amt: Optional[str] = ""
    cur_id: Optional[str] = ""
    chnl_typ: Optional[str] = ""
    narrat: Optional[str] = ""
    originating_acc_holder_name: Optional[str] = ""
    trxn_code: Optional[str] = ""
    stat: Optional[str] = ""
    co_id: Optional[str] = ""
    schd_id: Optional[str] = ""
    bulk_id: Optional[str] = ""
    tnx_type: Optional[str] = ""
    network_type: Optional[str] = ""
    acc_cur: Optional[str] = ""
    converted_amt: Optional[str] = ""
    is_foreign: Optional[str] = ""
    resp_code: Optional[str] = ""
    resp_desc: Optional[str] = ""
    receiver_first_name: Optional[str] = ""
    receiver_middle_name: Optional[str] = ""
    receiver_last_name: Optional[str] = ""
    receiver_mobile_no: Optional[str] = ""
    purpose: Optional[str] = ""
    optional_1: Optional[str] = ""
    optional_2: Optional[str] = ""
    optional_3: Optional[str] = ""
    optional_4: Optional[str] = ""
    optional_5: Optional[str] = ""
    optional_6: Optional[str] = ""
    optional_7: Optional[str] = ""
    optional_8: Optional[str] = ""
    optional_9: Optional[str] = ""
    optional_10: Optional[str] = ""
    optional_11: Optional[str] = ""
    optional_12: Optional[str] = ""
    optional_13: Optional[str] = ""
    optional_14: Optional[str] = ""
    optional_15: Optional[str] = ""
    sender_nationality: Optional[str] = ""
    claimcode: Optional[str] = ""
    sender_first_name: Optional[str] = ""
    sender_last_name: Optional[str] = ""
    sender_mobile_number: Optional[str] = ""
    sender_address: Optional[str] = ""
    ret_ref_id: Optional[str] = ""
    receiver_address: Optional[str] = ""
    ext_batch_id: Optional[str] = ""
    ext_rcvr_bnk_id: Optional[str] = ""
    ext_rcvr_bnk_name: Optional[str] = ""
    ext_trx_stat: Optional[str] = ""
    ext_trx_desc: Optional[str] = ""
    orig_trxn_no: Optional[str] = ""
    last_modified_by: Optional[str] = ""
    last_modified_date: Optional[str] = ""
    load_datetime: Optional[datetime] = None

    @field_validator("last_modified_date", "chal_valdt", mode="before")
    @classmethod
    def convert_dates(cls, v):
        return to_gmt8(v)
